#!/usr/bin/env node
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const envPath = resolve(root, ".env");
const outPath = resolve(root, "extension/src/shared/llm/secrets.generated.ts");

function parseEnv(text) {
  const env = {};
  for (const line of text.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const idx = trimmed.indexOf("=");
    if (idx === -1) continue;
    env[trimmed.slice(0, idx).trim()] = trimmed.slice(idx + 1).trim();
  }
  return env;
}

function pick(env, ...keys) {
  for (const key of keys) {
    if (env[key]) return env[key];
  }
  return "";
}

let env = {};
try {
  env = parseEnv(readFileSync(envPath, "utf8"));
} catch {
  console.warn("sync-llm-env: no .env file; writing empty secrets template");
}

const geminiApiKey = pick(env, "GEMINI_API_KEY", "IMPLEMENTO_LLM_API_KEY");
const openrouterApiKey = pick(env, "OPENROUTER_API_KEY", "IMPLEMENTO_LLM_BACKUP_API_KEY", "IMPLEMENTO_LLM_HARD_TASK_API_KEY");

const content = `// AUTO-GENERATED by scripts/sync-llm-env.mjs — do not edit
// Rebuild after changing .env: npm run build

export const BUILD_LLM_SECRETS = {
  geminiApiKey: ${JSON.stringify(geminiApiKey)},
  openrouterApiKey: ${JSON.stringify(openrouterApiKey)},
  geminiApiUrl: ${JSON.stringify(
    pick(env, "IMPLEMENTO_LLM_API_URL") ||
      "https://generativelanguage.googleapis.com/v1beta/openai/chat/completions",
  )},
  openrouterApiUrl: ${JSON.stringify(
    pick(env, "IMPLEMENTO_LLM_BACKUP_API_URL", "IMPLEMENTO_LLM_HARD_TASK_API_URL") ||
      "https://openrouter.ai/api/v1",
  )},
  defaultModel: ${JSON.stringify(pick(env, "IMPLEMENTO_LLM_MODEL") || "gemini-3.5-flash")},
  defaultTemperature: ${Number(pick(env, "IMPLEMENTO_LLM_TEMPERATURE") || "0.2")},
  openrouterNanoModel: ${JSON.stringify(
    pick(env, "IMPLEMENTO_LLM_BACKUP_MODEL") || "openai/gpt-5.4-nano",
  )},
  hardTaskModel: ${JSON.stringify(
    pick(env, "IMPLEMENTO_LLM_HARD_TASK_MODEL") || "openai/gpt-5.6-sol-pro",
  )},
  hardTaskMaxDailyUsd: ${Number(pick(env, "IMPLEMENTO_LLM_HARD_TASK_MAX_DAILY_USD") || "1")},
} as const;
`;

writeFileSync(outPath, content);
console.log(`sync-llm-env: wrote ${outPath}`);
